project_id = "lnzhonyvlrtwlzzxhlao"

[functions.get-available-slots]
verify_jwt = false

[functions.create-reservation]
verify_jwt = false

[functions.cancel-reservation]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = false